apiVersion: v1
kind: Service
metadata:
  name: kubepi
  namespace: kubepi-system
  labels:
    app.kubernetes.io/name: kubepi
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kubepi
  ports:
    - name: https
      port: 443
      targetPort: https
      nodePort: 30444
      protocol: TCP
