hostname: 10.144.66.139

networkExposure:
  type: none

ingress:
  enabled: false
  servicePort: 443
  tls:
    source: rancher

service:
  type: NodePort
  disableHTTP: true

replicas: 1
priorityClassName: jasper-service-high

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi

tls: ingress
privateCA: false
systemDefaultRegistry: 10.144.66.139:35000
useBundledSystemChart: true
postDelete:
  enabled: false

image:
  tag: v2.15.0@sha256:59d2643bdf3b76bfbc90410aff1f2b08765ac741d3d2349673381dcd685bf5f1
