hostname: 10.144.66.139

networkExposure:
  type: none

ingress:
  enabled: false
  servicePort: 443
  tls:
    source: rancher

service:
  type: NodePort
  disableHTTP: true

replicas: 1
priorityClassName: jasper-service-high

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi

tls: ingress
privateCA: false
systemDefaultRegistry: 10.144.66.139:35000
useBundledSystemChart: true
postDelete:
  enabled: false

image:
  tag: v2.15.0@sha256:8b1b2c65d5acd4abbd7709ac4589b0fed66e576f0e54278705b5754304c5a933
