---
kube_version: 1.35.4
container_manager: containerd
containerd_version: 2.2.3
etcd_deployment_type: host
etcd_version: 3.6.10
kube_network_plugin: cilium
cilium_version: 1.19.3
cilium_operator_image_repo: quay.io/cilium/operator-generic
cilium_enable_hubble: false
cilium_deploy_additionally: false
kube_proxy_mode: ipvs
kube_vip_enabled: false
loadbalancer_apiserver_localhost: false
dns_mode: coredns
enable_dns_autoscaler: true
enable_nodelocaldns: true
kube_network_plugin_multus: false
helm_enabled: false
registry_enabled: false
metrics_server_enabled: false
local_path_provisioner_enabled: false
local_volume_provisioner_enabled: false
cert_manager_enabled: false
gateway_api_enabled: false
prometheus_operator_crds_enabled: false
csi_snapshot_controller_enabled: false
cinder_csi_enabled: false
aws_ebs_csi_enabled: false
argocd_enabled: false
gvisor_enabled: false
kata_containers_enabled: false
crun_enabled: false
youki_enabled: false
